GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

DELETE http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTk3MDUwLCJpYXQiOjE3NTUxOTY3NTAsImp0aSI6IjU4NmZmYTMxZWYwNzRiODNhMDI0OTczZTRlMjBjYWYwIiwidXNlcl9pZCI6IjEifQ.OJxQPRU1HIQS8a30jsB-Wyf-QfnjHKx7_7Jv18_GMI0

{
    "name": "Televison",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTQzNjc1LCJpYXQiOjE3NTUxNDMzNzUsImp0aSI6ImViZjA5N2UxNmE3ZTQ0MTg4N2NkODkwNDgwMWM1Mjg1IiwidXNlcl9pZCI6IjEifQ.-4I_UsqQf-uEEgEPNWdtw6z9st5G_O5s253PkpZIqWk

{
    "name": "Televison",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTI4MjI3NywiaWF0IjoxNzU1MTk1ODc3LCJqdGkiOiI4OTVmZDZlZWFmNDg0NTFkODU4YzhiMWE4OTUyNDVjZiIsInVzZXJfaWQiOiIxIn0.OzVCAn8Kxed4KdsITkLkUX1gcoE4cAaVtBHa3r5lygE"
}
